import { useState } from 'react';
import { useApp } from '../context/AppContext';
import { getOldestPostDate } from '../utils/helpers';

const TT_DATE_POSTED = { '': '0', '2d': '2', '3d': '3', '7d': '7' };

export function useMasterScraper() {
  const {
    apiKey,
    ytActorId,
    ttActorId,
    fbActorId,
    igActorId,
    gnActorId,
    fetchActorItems,
    tagItems,
    setYtData,
    setTtData,
    setFbData,
    setIgData,
    setGnData,
  } = useApp();

  const [queries, setQueries] = useState([]);
  const [maxResults, setMaxResults] = useState(10);
  const [dateRange, setDateRange] = useState('7d');
  const [ttSearchType, setTtSearchType] = useState('keyword');
  const [igSearchType, setIgSearchType] = useState('user');
  const [gnTimeframe, setGnTimeframe] = useState('7d');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [status, setStatus] = useState({});

  const run = async () => {
    if (queries.length === 0) { setError('Agrega al menos una búsqueda.'); return; }
    if (!apiKey.trim()) { setError('Ingresa tu API Key de APIFY en Configuración.'); return; }

    const oldestDate = getOldestPostDate(dateRange);
    const tasks = [
      {
        key: 'youtube',
        enabled: Boolean(ytActorId.trim()),
        runTask: async () => {
          const input = {
            downloadSubtitles: false, hasCC: false, hasLocation: false, hasSubtitles: false,
            is360: false, is3D: false, is4K: false, isBought: false,
            isHD: false, isHDR: false, isLive: false, isVR180: false,
            maxResultStreams: 0, maxResults, maxResultsShorts: 0,
            preferAutoGeneratedSubtitles: false, saveSubsToKVS: false,
            searchQueries: queries,
            sortVideosBy: 'POPULAR', startUrls: [],
            subtitlesLanguage: 'en', subtitlesFormat: 'srt',
            ...(oldestDate && { oldestPostDate: oldestDate }),
          };
          const items = await fetchActorItems(ytActorId, input);
          setYtData(prev => [...prev, ...tagItems(items)]);
          return `${items.length} resultados`;
        },
      },
      {
        key: 'tiktok',
        enabled: Boolean(ttActorId.trim()),
        runTask: async () => {
          const base = {
            commentsPerPost: 0, excludePinnedPosts: false,
            maxFollowersPerProfile: 0, maxFollowingPerProfile: 0,
            maxProfilesPerQuery: 1000, maxRepliesPerComment: 0,
            proxyCountryCode: 'None', resultsPerPage: maxResults,
            scrapeRelatedVideos: false,
            searchDatePosted: TT_DATE_POSTED[dateRange] ?? '0',
            searchSection: '/video', searchSorting: '0',
            shouldDownloadAvatars: false, shouldDownloadCovers: false,
            shouldDownloadMusicCovers: false, shouldDownloadSlideshowImages: false,
            shouldDownloadVideos: false, topLevelCommentsPerPost: 0,
            profileScrapeSections: ['videos'], profileSorting: 'latest',
            downloadSubtitlesOptions: 'NEVER_DOWNLOAD_SUBTITLES',
            maxResults,
          };
          const input = ttSearchType === 'hashtag'
            ? { ...base, hashtags: queries }
            : { ...base, searchQueries: queries };
          const items = await fetchActorItems(ttActorId, input);
          setTtData(prev => [...prev, ...tagItems(items)]);
          return `${items.length} resultados`;
        },
      },
      {
        key: 'facebook',
        enabled: Boolean(fbActorId.trim()),
        runTask: async () => {
          const batches = await Promise.all(
            queries.map(query => fetchActorItems(fbActorId, {
              query,
              max_posts: maxResults,
              search_type: 'posts',
              recent_posts: false,
            }))
          );
          const items = batches.flat();
          setFbData(prev => [...prev, ...tagItems(items)]);
          return `${items.length} resultados`;
        },
      },
      {
        key: 'instagram',
        enabled: Boolean(igActorId.trim()),
        runTask: async () => {
          const batches = await Promise.all(
            queries.map(query => fetchActorItems(igActorId, {
              addParentData: false,
              resultsLimit: maxResults,
              resultsType: 'posts',
              search: query,
              searchLimit: 10,
              searchType: igSearchType,
            }))
          );
          const items = batches.flat();
          setIgData(prev => [...prev, ...tagItems(items)]);
          return `${items.length} resultados`;
        },
      },
      {
        key: 'google-news',
        enabled: Boolean(gnActorId.trim()),
        runTask: async () => {
          const items = await fetchActorItems(gnActorId, {
            decodeUrls: false,
            extractDescriptions: true,
            extractImages: true,
            keywords: queries,
            maxArticles: maxResults,
            proxyConfiguration: { useApifyProxy: true },
            region_language: 'MX:es-419',
            timeframe: gnTimeframe,
            topics: [],
            topicUrls: [],
          });
          setGnData(prev => [...prev, ...tagItems(items)]);
          return `${items.length} resultados`;
        },
      },
    ];

    setLoading(true);
    setError('');
    setStatus({});

    try {
      const results = await Promise.allSettled(
        tasks.map(async task => {
          if (!task.enabled) return { key: task.key, message: 'omitido: falta actor ID' };
          const message = await task.runTask();
          return { key: task.key, message };
        })
      );

      const nextStatus = {};
      const failures = [];

      results.forEach((result, index) => {
        const key = tasks[index].key;
        if (result.status === 'fulfilled') {
          nextStatus[key] = result.value.message;
          return;
        }
        nextStatus[key] = `error: ${result.reason?.message || 'falló la ejecución'}`;
        failures.push(`${key}: ${result.reason?.message || 'falló la ejecución'}`);
      });

      setStatus(nextStatus);
      if (failures.length === tasks.length) {
        setError(failures.join(' | '));
      }
    } finally {
      setLoading(false);
    }
  };

  return {
    queries, setQueries,
    maxResults, setMaxResults,
    dateRange, setDateRange,
    ttSearchType, setTtSearchType,
    igSearchType, setIgSearchType,
    gnTimeframe, setGnTimeframe,
    loading, error, status,
    run,
  };
}