import { useState } from 'react';
import { useApp } from '../context/AppContext';
import { getOldestPostDate } from '../utils/helpers';
import { buildSheet, downloadWorkbook } from '../utils/excelHelpers';
import { YT_EXCEL_COLS } from '../config/columns';

export function useYouTubeScraper() {
  const { apiKey, ytActorId, fetchActorItems, tagItems, ytData, setYtData } = useApp();

  const [queries,   setQueries]   = useState([]);
  const [max,       setMax]       = useState(50);
  const [dateRange, setDateRange] = useState('');
  const [loading,   setLoading]   = useState(false);
  const [error,     setError]     = useState('');
  const [progress,  setProgress]  = useState('');
  const [exporting, setExporting] = useState(false);

  const run = async () => {
    if (queries.length === 0) { setError('Agrega al menos una búsqueda.'); return; }
    if (!apiKey.trim()) { setError('Ingresa tu API Key de APIFY en Configuración.'); return; }
    setLoading(true);
    setError('');
    const oldestDate = getOldestPostDate(dateRange);
    try {
      for (let idx = 0; idx < queries.length; idx++) {
        setProgress(`${idx + 1} / ${queries.length}: "${queries[idx]}"`);
        const input = {
          downloadSubtitles: false, hasCC: false, hasLocation: false, hasSubtitles: false,
          is360: false, is3D: false, is4K: false, isBought: false,
          isHD: false, isHDR: false, isLive: false, isVR180: false,
          maxResultStreams: 0, maxResults: max, maxResultsShorts: 0,
          preferAutoGeneratedSubtitles: false, saveSubsToKVS: false,
          searchQueries: [queries[idx]],
          sortVideosBy: 'POPULAR', startUrls: [],
          subtitlesLanguage: 'en', subtitlesFormat: 'srt',
        };
        if (oldestDate) input.oldestPostDate = oldestDate;
        const items = await fetchActorItems(ytActorId, input);
        setYtData(prev => [...prev, ...tagItems(items)]);
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
      setProgress('');
    }
  };

  const exportExcel = async () => {
    setExporting(true);
    try {
      const { default: ExcelJS } = await import('exceljs');
      const wb = new ExcelJS.Workbook();
      await buildSheet(wb, 'YouTube', ytData, YT_EXCEL_COLS,
        item => `https://img.youtube.com/vi/${item.id}/mqdefault.jpg`);
      await downloadWorkbook(wb, 'youtube.xlsx');
    } catch (err) {
      setError('Error al exportar: ' + err.message);
    } finally {
      setExporting(false);
    }
  };

  return { queries, setQueries, max, setMax, dateRange, setDateRange, loading, error, progress, exporting, run, exportExcel };
}
